### ISSUE TITLE
You found it!

### ISSUE THREAD

**Issue by daid** [verhoevenv/jumpnbump-wii#2]
I thought this was lost forever due to harddrive failure on my side.

**Comment by verhoevenv** [comment]
Haha, hey Daid, this is Amarth, I did the original port. 13 years ago, my god. This brings back memories! Good to hear from you!

Yeah the code is just here for safekeeping and archival, I'm not doing anything with it anymore. My Wii died a few years ago and even though I loved the machine and the homebrew scene, I guess that's in the past now for me.

**Comment by daid** [comment]
Sort of same here, I have two wii's still, and they still work. But haven't touched them or homebrew wii in years. So not surprised that you haven't done anything with it. I was just surprised my code changes where not lost forever. Archived one of my other projects a while back when I encountered it in a lost folder: https://github.com/daid/GuitarsOnFire but Jump n Bump wasn't there with it.

I'm currently active in the gameboy development homebrew scene, which is quite a fun scene. So still doing silly things with nintendo consoles :)
